### ISSUE TITLE
It can not work with .ai file just include path

### ISSUE THREAD

**Issue by drink-crow** [gomi42/ShapeConverter#1]
A nice job with pretty UI
I have several attempts, it work with PSD file. But it look like that can not parse the .ai file whitch only have path

**Comment by gomi42** [comment]
Your file seems to be a special case. Do you see a chance to send it to me? Non disclosure is guaranteed. In case send it to gomi42 at gmx dot de.

**Comment by drink-crow** [comment]
I sent it from mail. I create pattern in Photoshop cc 64bit on Win10, and then access command: File -> Export -> Path to illustrator

**Comment by gomi42** [comment]
Interesting .AI file that I wasn't aware of. It's format is not a standard .AI file, it's very similar to the EPS file format but with different commands. I'm very sorry but .AI files exported as Path to Illustrator aren't supported yet.
