### ISSUE TITLE
Why can’t I fork?

### ISSUE THREAD

**Issue by MikeCodesDotNET** [gomi42/ShapeConverter#2]
As per the title. The license doesn’t have restrictions on forks so I’m a bit confused why you’ve stated that you don’t want the project to be forked.

**Comment by gomi42** [comment]
Oh, I apologize for the confusion. Of course you can fork and you are encouraged to make proposals or to improve the ShapeConverter (based on the license you even need to publish your work).

I only want to avoid kind of "empty" forks. Forks that are created for nothing and that just pollute the fork list. That's all. Having that said I'm looking forward to seeing your proposals/improvements.

**Comment by MikeCodesDotNET** [comment]
Understood! I was looking for a project relating to imaging for playing with WinUI.
