### ISSUE TITLE
color 32bit or cmyk

### ISSUE THREAD

**Issue by car520120** [gomi42/ShapeConverter#3]
color 32bit or cmyk is paser is ok?

**Comment by gomi42** [comment]
Could you please give more details what you are asking.

**Comment by car520120** [comment]
> Could you please give more details what you are asking.
https://github.com/car520120/ShapeConverterRes.git 
you can look at then cmyk.ai and cmyk.png file!

**Comment by gomi42** [comment]
Ok, got it, the color is not correct. The ShapeConverter shows the hint "Colors are placeholder". You should take that very serious. That means that the ShapeConverter cannot 100% reproduce the colors. In general a CMYK color space cannot be correctly converted to an RGB color space without a profile. The ShapeConverter tries its best but it will always be an estimation. The solution is to embed the needed ICC profile (the ShapeConverter supports that) - its a setting in the Save dialog of Illustrator.
