### ISSUE TITLE
Question: Clarify More About Stream

### ISSUE THREAD

**Issue by broderickt2** [gomi42/ShapeConverter#4]
Hello,

I have read through the documentation and am trying to learn more about the stream input text box, the text box in the stream tab near the file input. I tried loading a System IO MemoryStream into this field but that failed. Note: I uploaded the same file just fine using the file upload control. Is this text box a specific geometry type stream or something like that? Is the “stream” one of the things generated in the tab results? What’s the expected input for the stream text box?

By the way, thanks for sharing this awesome library and providing any assistance you can.

**Comment by gomi42** [comment]
Hello,

I think there's a small misunderstanding. The "Stream" tab is the opposite way of the "File" tab. "Stream" in this context refers to "StreamGeometry" which is the light weight form of a "PathGeometry". While the "File" tab takes a file and converts it to either  "StreamGeometries" or "PathGeometries" (and more formats), the "Stream" tab takes a "StreamGeometry" (not an IO stream) and converts it to different formats. I have quite often the need to preview single "StreamGeometries" so I added the "Stream" tab - the main feature of the ShapeConverter is clearly the "File" tab.

You might want to try it. Enter the following "StreamGeometry" in the "Stream" tab and you'll get a preview (plus conversions to other formats) of the t-shirt: 

F1M92.63107,7.99048 L63.33318,0.00001 L36.66644,0.00001 L7.36856,7.99048 C3.01819,9.17728 0,13.12853 0,17.63825 L0,46.6669 C0,48.50772 1.49229,50.00038 3.33348,50.00038 L20.00015,50.00038 L20.00015,86.66682 L80.00023,86.66682 L80.00023,42.50042 L100,42.50042 L100,17.63825 C100,13.12853 96.98181,9.17728 92.63107,7.99048 z

**Comment by broderickt2** [comment]
@gomi42 Thanks for your explanation. I tried your example and that makes a lot of sense now.
